# Generated by Django 5.1.5 on 2025-04-03 18:40

import django.db.models.deletion
import django.utils.timezone
import json.encoder
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-processed_at'], 'permissions': [('view_sensitive_payment', 'Can view unmasked payment data')], 'verbose_name': 'Payment Record', 'verbose_name_plural': 'Payment Records'},
        ),
        migrations.AddField(
            model_name='payment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of payer', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in the specified currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_last4',
            field=models.CharField(help_text='Last 4 digits of payment card', max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', help_text='3-letter currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When payment was processed'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_request',
            field=models.JSONField(default=dict, encoder=json.encoder.JSONEncoder, help_text='Original payment request data (encrypted)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], help_text='Current payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(help_text='Unique transaction identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['processed_at'], name='payments_pa_process_0233b1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
    ]
