# Generated by Django 5.1.5 on 2025-04-03 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_payment_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-processed_at'], 'verbose_name': 'Payment Record', 'verbose_name_plural': 'Payment Records'},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_user_id_01767a_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_process_0233b1_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_transac_8e9d99_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_last4',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_request',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
