# Generated by Django 5.1.5 on 2025-04-04 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount charged in the specified currency', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_last4',
            field=models.CharField(help_text='Last 4 digits of the payment card', max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', help_text='ISO 4217 currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when payment was processed'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='raw_request',
            field=models.JSONField(default=dict, help_text='Sanitized payment request data (sensitive fields are masked)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded')], help_text='Current status of the payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(help_text='Unique transaction identifier from payment processor', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_8e9d99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'processed_at'], name='payments_pa_user_id_daa0e9_idx'),
        ),
    ]
